# Add source files here
EXECUTABLE	:= matrixm
# Cuda source files (compiled with cudacc)
CUFILES		:= matrixm.cu


# C/C++ source files (compiled with gcc / c++)
CCFILES		:= 

################################################################################
# Rules and targets

include ../../common/common.mk
