# Add source files here
EXECUTABLE	:= filter
# Cuda source files (compiled with cudacc)
CUFILES_sm_20			:= filter.cu 
CUDEPS				:= filter_kernel.cu

# C/C++ source files (compiled with gcc / c++)
CCFILES		:= 

################################################################################
# Rules and targets

include ../../common/common.mk
